---
- include_vars: "{{ ansible_os_family }}.yml"

- include: Debian.yml
  when: ansible_os_family == "Debian"

- include: conf.yml

- name: Delete old slave info to ensure clean startup of Chronos after an upgrade
  file: path=/tmp/mesos/meta/slaves/latest state=absent

